spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: test
    driverClassName: org.postgresql.Driver